version: "3.7"

services:
  #NO IMPL OF CONFIG SERVER FOR NOW
  #  configserver:
  #    build: ./config-server
  #    restart: always
  #    ports:
  #      - "8081:8081"

  postgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRESQL_PASSWORD: root

  mongodb:
    image: mongo:5.0.9
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: heos971-gwada@hotmail.fr
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: mongodb

  microservicepatients:
    container_name: mspatients
    build: ./microservice-patients
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - postgresql
      #      - configserver
    command:
      - sh -c './wait-for mysql:3306 -- npm start'

  microservicenotes:
    container_name: msnotes
    build: ./microservice-notes
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
      #      - configserver
      - microservicepatients
    command:
      - sh -c './wait-for mongodb:27017 -- npm start'
      - sh -c './wait-for microservicepatients:8081 -- npm start'

  microserviceassessment:
    container_name: msreport
    build: ./microservice-report
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - microservicepatients
      - microservicenotes
      #      - configserver
      - eurekaserver
    command:
      - sh -c './wait-for microservicepatients:8081 -- npm start'
      - sh -c './wait-for microservicenotes:8082 -- npm start'
